# Generated by Django 2.0.5 on 2018-10-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181015_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaopostagem',
            name='servicos',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Servico'),
        ),
    ]
