# Generated by Django 2.0.5 on 2018-10-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181016_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaopostagem',
            name='codDR',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
